language: java
jdk:
 - oraclejdk8
sudo: false

addons:
  sonarcloud:
    organization: "crejczyk-github"
    token:
      secure: "8a8d1cef333dd947418ef45e316b2fa839ed2574"
      
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
install: true

services: mongodb
script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar